name: Build and Push Docker Image

on:
    push:
        branches:
            - main

jobs:
    build-and-push-docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker image
              run: |
                  sudo docker build . -t ${{ secrets.DOCKER_USERNAME }}/nodeimage:latest
                  sudo docker push ${{ secrets.DOCKER_USERNAME }}/nodeimage:latest

            - name: Execute SSH commmands on remote server
              uses: JimCronqvist/action-ssh@master
              with:
                  hosts: "ubuntu@15.206.187.32:22"
                  privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
                  debug: false
                  command: |
                      echo '${{ secrets.DOCKER_PASSWORD }}' | sudo docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

# firstly pull the docker image second make sure it is not running if running delete the container or restart the container 
            - name: Run docker image to Container
              run: |
                  sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nodeimage:latest
                  sudo docker rm -f nodecontainer
                  sudo docker run -d -p 5000:2001 --name nodecontainer ${{ secrets.DOCKER_USERNAME }}/nodeimage

# sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nodeimage:latest
# sudo docker rm -f nodecontainer
# sudo docker run -d -p 5000:2001 --name nodecontainer ${{ secrets.DOCKER_USERNAME }}/nodeimage
